# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZwUM7sx57--iCNEB4Z1D_e4Ygh5jBxg
"""

# -*- coding: utf-8 -*-
"""
Climate Change Temperature Analysis
Data Processing Script
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("GlobalLandTemperaturesByCountry.csv")

print("RAW DATA OVERVIEW")
print("Initial Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)


# -----------------------------------
# CHECK MISSING VALUES
# -----------------------------------

missing_before = df.isnull().sum()

print("\nMissing Values (Before Cleaning):")
print(missing_before)

print("Total Missing (Before):", missing_before.sum())


# -----------------------------------
# HANDLE MISSING VALUES
# -----------------------------------

print("\nHANDLING MISSING VALUES")

numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(include=["object"]).columns


# Fill numeric columns with mean
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())


# Fill categorical columns with mode
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])


missing_after = df.isnull().sum()

print("\nMissing Values (After Cleaning):")
print(missing_after)

print("Total Missing (After):", missing_after.sum())

print("\nMissing Values Reduced By:",
      missing_before.sum() - missing_after.sum())


# -----------------------------------
# REMOVE DUPLICATES
# -----------------------------------

print("\nDUPLICATE REMOVAL")

before_dup = df.shape[0]

duplicate_count = df.duplicated().sum()

print("Duplicate Rows Found:", duplicate_count)

df = df.drop_duplicates()

after_dup = df.shape[0]

print("Rows Before Removing Duplicates:", before_dup)
print("Rows After Removing Duplicates:", after_dup)

print("Total Duplicates Removed:", before_dup - after_dup)


# -----------------------------------
# OUTLIER DETECTION (IQR METHOD)
# -----------------------------------

print("\nOUTLIER DETECTION (IQR METHOD)")

before_outlier = df.shape[0]

print("Rows Before Outlier Removal:", before_outlier)


def remove_outliers_iqr(data, columns):

    for col in columns:

        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)

        IQR = Q3 - Q1

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        data = data[
            (data[col] >= lower_bound) &
            (data[col] <= upper_bound)
        ]

    return data


df = remove_outliers_iqr(df, numeric_cols)

after_outlier = df.shape[0]

print("Rows After Outlier Removal:", after_outlier)

print("Outliers Removed:", before_outlier - after_outlier)


# -----------------------------------
# DATA TRANSFORMATION
# -----------------------------------

print("\nDATA TRANSFORMATION")

df['dt'] = pd.to_datetime(df['dt'])

df['Year'] = df['dt'].dt.year
df['Month'] = df['dt'].dt.month

print("New Columns Added: Year, Month")


# -----------------------------------
# DATA AGGREGATION
# -----------------------------------

yearly_avg_temp = df.groupby("Year")[[
    "AverageTemperature"
]].mean().reset_index()


country_avg_temp = df.groupby("Country")[[
    "AverageTemperature"
]].mean().reset_index()


print("\nYearly Average Temperature (Preview):")

print(yearly_avg_temp.head())


# -----------------------------------
# SAVE CLEAN DATA
# -----------------------------------

df.to_csv("temperature_cleaned.csv", index=False)

yearly_avg_temp.to_csv("temperature_yearly_avg.csv", index=False)

country_avg_temp.to_csv("temperature_country_avg.csv", index=False)


print("\nFINAL DATASET READY")

print("Final Shape:", df.shape)
